export const schools = [
  {
    ID: 1,
    Name: 'ACS_international_School',
    Price: 330,
    Current_Inventory: 225,
    Backorder: 0,
    Manufacturing: 10,
    Category: 'Video Players',
    ImageSrc: 'images/products/1.png',
  },
  {
    ID: 3,
    Name: 'Our_Lady_Star_Of_The_Sea',
    Price: 2400,
    Current_Inventory: 0,
    Backorder: 0,
    Manufacturing: 0,
    Category: 'Televisions',
    ImageSrc: 'images/products/3.png',
  },
  {
    ID: 4,
    Name: 'St_Marks',
    Price: 1600,
    Current_Inventory: 77,
    Backorder: 0,
    Manufacturing: 55,
    Category: 'Televisions',
    ImageSrc: 'images/products/4.png',
  },
  {
    ID: 5,
    Name: 'Parkside_Community_Primary_School',
    Price: 1450,
    Current_Inventory: 445,
    Backorder: 0,
    Manufacturing: 0,
    Category: 'Televisions',
    ImageSrc: 'images/products/5.png',
  },
  {
    ID: 1,
    Name: 'ACS_international_School',
    Price: 330,
    Current_Inventory: 225,
    Backorder: 0,
    Manufacturing: 10,
    Category: 'Video Players',
    ImageSrc: 'images/products/1.png',
  },
  {
    ID: 3,
    Name: 'Our_Lady_Star_Of_The_Sea',
    Price: 2400,
    Current_Inventory: 0,
    Backorder: 0,
    Manufacturing: 0,
    Category: 'Televisions',
    ImageSrc: 'images/products/3.png',
  },
  {
    ID: 4,
    Name: 'St_Marks',
    Price: 1600,
    Current_Inventory: 77,
    Backorder: 0,
    Manufacturing: 55,
    Category: 'Televisions',
    ImageSrc: 'images/products/4.png',
  },
  {
    ID: 5,
    Name: 'Parkside_Community_Primary_School',
    Price: 1450,
    Current_Inventory: 445,
    Backorder: 0,
    Manufacturing: 0,
    Category: 'Televisions',
    ImageSrc: 'images/products/5.png',
  },
]
